# Conclusion

After seeing all the relationships between box-office and budget, as well as viewing the actors' general career trends before and after joining the MCU, we conclude that featuring in an MCU film does not guarantee a super significant change in terms of starring in successful movies. The majority of actors who appear in the MCU usually have a fairly rich filmography beforehand, many of which began in a TV Series, then build up with a few, or in some cases many, strong performances in larger films. Thus, with the exception of a few outliers, there does not really seem to be a drastic change of career arc following an MCU appearance.

Further, there does not end up being a strong relationship between the performance of MCU movies featuring particular actors with the performance of the movies that those actors starred in outside of the MCU. That is to say, the consistent box-office success that the MCU enjoys seems to be relatively independent of the actors they choose to cast.

It seems as though these MCU films unerringly result in huge box-office return, even in their "less successful" entries. Even when it may seem as though the MCU has finally hit a rut and fallen back down to Earth with a few movies in Phase 4 that returned lower-than-expected box-office numbers on their lofty standards, a much wider phenomenon was afoot, namely the Covid-19 pandemic that lowered box-office numbers across all movies. Beyond that, Disney seems to recognize when they are getting to a point in their saga that will attract a much wider audience, so there is a pretty solid correlation between larger budgets and higher box-office returns.

The MCU is truly a rare occurrence in filmmalking. The ability to create an interconnected story across so many movies, while keeping each individual film entertaining enough such that there is practically never a misfire in terms of box-office success or rating, is quite impressive. You might even say that the universe that has been created is something to "marvel" at.