---
title: "Currency Conversion"
author: "Andrew Ward"
date: "4/18/2022"
output: html_document
---

```{r}
library(readr)
library(tidyverse)
filmography_awards_masterfile <- read_csv("filmography_awards-masterfile.csv")
head(filmography_awards_masterfile)

```

```{r}
unique_currency <- filmography_awards_masterfile %>%
  distinct(budget_currency)

unique_currency

unique2_currency <- filmography_awards_masterfile %>%
  distinct(boxoffice_currency)

unique2_currency

```


```{r}
# 1 GBP = 1.3 USD
# 1 EUR = 1.08 USD
# 1 AUD = 0.73 USD
# 1 FRF = 0.165 USD
# 1 NGN = 0.0024 USD

```

```{r}
converted_currency <- filmography_awards_masterfile %>%
  mutate(budget_USD = ifelse(budget_currency == "USD", budget, ifelse(budget_currency == "GBP", budget * 1.3, ifelse(budget_currency == "EUR", budget * 1.08, ifelse(budget_currency == "AUD", budget * .73, ifelse(budget_currency == "FRF", budget * .165, ifelse(budget_currency == "NGN", budget * .0024, NA)))))))

converted_currency <- converted_currency %>%
  dplyr::select(actor_id, actor_name, category, title_id, title, year, release_date, type, budget_currency, budget, budget_USD, boxoffice_currency, `World-wide`, International, Domestic, MCU_film, award_name, award_category, event_name, winner, nomination_year)

converted_currency <- converted_currency %>%
  mutate(release_date = as.Date(release_date))

converted_currency
```

```{r}
write_csv(converted_currency, "filmography_awards-masterfile.csv")
```



