--- 
title: "MCU Actor Analysis"
author: "Katrina Gross & Andy Ward"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We were interested in budget and box office trends for movies. Specifically, we wanted to explore the division between actors performing in large budget movies and smaller, low-budget projects. There has been recent [discussion](https://www.newyorker.com/culture/the-front-row/2022-oscar-predictions-who-will-win-versus-who-should) about whether directors who join high-production value projects with projected high box offices do so in order to work on smaller “passion projects”. We chose to look at the highest grossing film franchise - the Marvel Cinematic Universe (MCU). We wanted to see if this hypothesis proved to be true for actors in the MCU. We set out to answer a few questions: 1) When do MCU actors join the MCU in their career? 2) How do high box-office movies enable actors to work on low-budget projects? 3) Does the fame that comes with featuring in a big box-office film cause the actors' future films to be more successful? 4) Is there a correlation between box-office sucess, film budget, and the fame of the starring actors for these movies?

We are also interested in this topic as we are both MCU fans.
