---
title: "Actor Filmography"
author: "Katrina Gross"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(stringr)

library(httr) # need for API
library(jsonlite)

library(here)
```

In this file:

- get actor ids
- get filmography for actors

### Add Key HERE
store in text file and read in once
```{r}
key <- read.delim(here("../api_key.txt"), header = FALSE)
key <- key$V1

```

### Top Cast

```{r}

mcu_movies <- read_csv("../data_exports/MCU_ids.csv")

mcu_movies[c('actor1', 'actor2')] <- str_split_fixed(mcu_movies$d.s, ',', 2)

actor1 <- mcu_movies %>% pull(actor1)
actor2 <- mcu_movies %>% pull(actor2)

actors_add <- c("Sebastian Stan","Elizabeth Olsen", "Anthony Mackie", "Mark Ruffalo", "Paul Bettany", 
                "Don Cheadle", "Jeremy Renner")

main_actors <- c(actor1, actor2, actors_add)
main_actors <- unique(main_actors)

rm(actor1, actor2)

```

### Actor Names to use

```{r}
# using short list

main_cast_list<- unique(main_actors)
cast_dict1 = list()

for(name in main_cast_list){
  cast_temp_list = list(q = name)
  cast_dict1 = c(cast_dict1, cast_temp_list)
}

rm(cast_temp_list)

```


```{r}

# use to get actor id

url <- "https://online-movie-database.p.rapidapi.com/auto-complete"

headers <- c(
    'x-rapidapi-host' = "online-movie-database.p.rapidapi.com",
    'x-rapidapi-key' = key)

cast_ids <- data.frame(matrix(ncol = 12))
cols <- c("d.i", "d.id", "d.l", "d.q", "d.rank", "d.s",  "d.v", "d.vt", "d.y",  
                      "d.yr", "q", "v"  )

colnames(cast_ids) <- cols

for(i in 1:length(cast_dict1)){
  response <- GET(url, add_headers(headers), query = cast_dict1[i])
  temp_data <- fromJSON(rawToChar(response$content))
  data_tidy <- data.frame(temp_data)
  cast_ids <- dplyr::bind_rows(cast_ids, data_tidy)
}

rm(response, temp_data, data_tidy)

```

```{r}

# clean the data

cast_master <- cast_ids %>%
  select(d.id, d.l, d.s, q) %>%
  filter(str_detect(d.id, "nm")) %>%
  filter(str_detect(d.s, "Actor") | str_detect(d.s, "Actress"))

# make sure names are the same

cast_master <- cast_master %>%
  dplyr::mutate(d.l = gsub("\\(.*?)", "", d.l),
                d.l = str_trim(d.l),
                q = str_trim(q),
                match = ifelse(d.l == str_to_title(q), 1, 0)) 

head(cast_master)
```


```{r}

actor_id_df <- cast_master %>%
  filter(match == 1) %>%
  dplyr::select(c(d.id, d.l)) %>%
  rename(actor_id = d.id, actor_name = d.l)

head(actor_id_df)

write_csv(actor_id_df, "../data_exports/Actor-Ids.csv")
```

## Cast Cast ID Dict

```{r}
# create cast id dict to be used in filmography and awards api

cast_ids <- cast_master %>%
  pull(`d.id`)
  
id_cast_dict = list()

for(id in cast_ids){
  temp_list = list(nconst = id)
  id_cast_dict = c(id_cast_dict, temp_list)
}

```


## Filmography

```{r}
# get cast filmography

url <- "https://online-movie-database.p.rapidapi.com/actors/get-all-filmography"

headers <- c(
    'x-rapidapi-host' = "online-movie-database.p.rapidapi.com",
    'x-rapidapi-key' = key)

film_df <- data.frame(matrix(ncol = 6))
colnames(film_df) <- c("actor_id", "film_list", "type", "status", "category", "title_ids")

for(i in 1:length(id_cast_dict)){
  response <- GET(url, add_headers(headers), query = id_cast_dict[i])
  temp_data2 <- fromJSON(rawToChar(response$content))
  film_list <- temp_data2[["filmography"]][["title"]]
  type <- temp_data2[["filmography"]][["titleType"]]
  status <- temp_data2[["filmography"]][["status"]]
  category <- temp_data2[["filmography"]][["category"]]
  title_ids <- temp_data2[["filmography"]][["id"]]
  #billing <- temp_data2[["filmography"]][["billing"]]
  df_temp <- data.frame(id_cast_dict[[i]], film_list, type, status, category, title_ids)
  colnames(df_temp) <- c("actor_id", "film_list", "type", "status", "category", "title_ids")
  film_df <- dplyr::bind_rows(film_df, df_temp)
}

#rm(df_temp, temp_data2, response, film_list, type, status, category, title_ids)

```


```{r}
head(film_df)
```
### Clean Filmography

```{r}

# clean filmography data

filmography_data <- film_df %>%
  drop_na(actor_id) %>%
  filter(category == "actor" | category == "actress") %>%
  filter(status == "released") %>%
  select(-status) %>%
  filter(type %in% c("movie", "tvSeries", "tvMiniSeries")) %>%
  dplyr::mutate(title_ids = gsub("\\/title/", "", title_ids),
                title_ids = gsub("\\/$", "", title_ids))

filmography_data <- filmography_data %>%
  left_join(actor_id_df) %>%
  dplyr::select(c(actor_id, actor_name, everything())) %>%
  distinct()

head(filmography_data)
dim(filmography_data)

rm(film_df)

write_csv(filmography_data, "../data_exports/Filmography-4-18.csv")
```

### Awards

```{r}
# get cast awards

url <- "https://online-movie-database.p.rapidapi.com/actors/get-awards"

headers <- c(
    'x-rapidapi-host' = "online-movie-database.p.rapidapi.com",
    'x-rapidapi-key' = key)

award_df <- data.frame(matrix(ncol = 7))
colnames(award_df) <- c("actor_id", "award_name", "award_category", "event_name", "winner", "year", "titles")

for(i in 1:length(id_cast_dict)){
  response <- GET(url, add_headers(headers), query = id_cast_dict[i])
  temp_data <- fromJSON(rawToChar(response$content))
  award_name <- temp_data[["resource"]][["awards"]][["awardName"]]
  award_category <- temp_data[["resource"]][["awards"]][["category"]]
  event_name <- temp_data[["resource"]][["awards"]][["eventName"]]
  winner <- temp_data[["resource"]][["awards"]][["isWinner"]]
  year <- temp_data[["resource"]][["awards"]][["year"]]
  # get titles 
  titles = list()
  for(j in 1:length(award_name)){
    title_temp <- temp_data[["resource"]][["awards"]][["nominations"]][["titles"]][[j]]['title']$title
    if(is.null(title_temp)){
      title_temp <- "NULL" # keep nulls to make list right length
    }
    titles[j] <- title_temp
  }
  titles <- unlist(titles)
  if(!is.null(award_name)){
      df_temp <- data.frame(id_cast_dict[[i]], award_name, award_category, event_name, winner, year, titles)
      colnames(df_temp) <- c("actor_id", "award_name", "award_category", "event_name", "winner", "year", "titles")
      award_df <- dplyr::bind_rows(award_df, df_temp)
  }
}

head(award_df)

#rm(response, temp_data, award_name, award_category, event_name, winner, year, titles, title_temp, df_temp)

```
### Clean Awards

```{r}

awards_tidy <- award_df %>%
  drop_na(actor_id) %>%
  #dplyr::filter(winner == TRUE) %>%
  dplyr::filter(grepl('Oscar|Emmy', award_name)) %>%
  left_join(actor_id_df) %>%
  dplyr::select(actor_id, actor_name, everything()) %>%
  mutate(winner = ifelse(winner, "Winner", "Nominated"))
         
write_csv(awards_tidy, "../data_exports/Actor_Awards_add.csv")
```

### Create query dict of titles

```{r}

id_list <- filmography_data %>%
  pull(title_ids)

id_list <- unique(id_list)

id_dict = list()

for(id in id_list){
  temp_list = list(tconst = id)
  id_dict = c(id_dict, temp_list)
}

```

### Business For Films
do in two chunks and then combine - for loop breaks if not

```{r}
url <- "https://online-movie-database.p.rapidapi.com/title/v2/get-business"

headers <- c(
    'x-rapidapi-host' = "online-movie-database.p.rapidapi.com",
    'x-rapidapi-key' = key)

business_master <- data.frame(matrix(ncol = 8))
cols <- c("area", "areaName", "total", "movie_id", "title", "year", "budget", "budget_curr")
colnames(business_master) <- cols

for(i in 1:length(id_dict)){
      
      print(paste("query: ", i, id_dict[i]))
      
      response <- GET(url, add_headers(headers), query = id_dict[i])
      temp_data <- fromJSON(rawToChar(response$content))
      
      if(length(temp_data[["titleBoxOffice"]]) > 0){
      
          title <- temp_data$titleBoxOffice$title
          year <- temp_data$titleBoxOffice$year
          
          if(is.null(title)) {title <- "NULL"}
          if(is.null(year)) {year <- 0}
          
          budget <- temp_data[['titleBoxOffice']][['budget']][['amount']]
          currency <- temp_data[['titleBoxOffice']][['budget']][['currency']]
          
          if(is.null(budget)) {budget <- 0}
          if(is.null(currency)) {currency <- "NULL"}
    
          gross <- temp_data[["titleBoxOffice"]][["gross"]][["aggregations"]]
          gross <- as.data.frame(gross)
          
          if(nrow(gross)==0){
            gross <- data.frame(matrix(ncol = 8))
            colnames(gross) <- cols
          }
          
          gross$movie_id <- id_dict[i]$tconst
          gross$title <- as.character(title)
          gross$year <- as.numeric(year)
          gross$budget <- as.numeric(budget)
          gross$budget_curr <- as.character(currency)
          
          business_master <- dplyr::bind_rows(business_master, gross)
    }
}

business_master_keep1 <- business_master

```

```{r}

# split into two because it breaks with too many queries

url <- "https://online-movie-database.p.rapidapi.com/title/v2/get-business"

headers <- c(
    'x-rapidapi-host' = "online-movie-database.p.rapidapi.com",
    'x-rapidapi-key' = key)

business_master <- data.frame(matrix(ncol = 8))
cols <- c("area", "areaName", "total", "movie_id", "title", "year", "budget", "budget_curr")
colnames(business_master) <- cols

for(i in 765:length(id_dict)){
      
      print(paste("query: ", i, id_dict[i]))
      
      response <- GET(url, add_headers(headers), query = id_dict[i])
      temp_data <- fromJSON(rawToChar(response$content))
      
      if(length(temp_data[["titleBoxOffice"]]) > 0){
      
          title <- temp_data$titleBoxOffice$title
          year <- temp_data$titleBoxOffice$year
          
          if(is.null(title)) {title <- "NULL"}
          if(is.null(year)) {year <- 0}
          
          budget <- temp_data[['titleBoxOffice']][['budget']][['amount']]
          currency <- temp_data[['titleBoxOffice']][['budget']][['currency']]
          
          if(is.null(budget)) {budget <- 0}
          if(is.null(currency)) {currency <- "NULL"}
    
          gross <- temp_data[["titleBoxOffice"]][["gross"]][["aggregations"]]
          gross <- as.data.frame(gross)
          
          if(nrow(gross)==0){
            gross <- data.frame(matrix(ncol = 8))
            colnames(gross) <- cols
          }
          
          gross$movie_id <- id_dict[i]$tconst
          gross$title <- as.character(title)
          gross$year <- as.numeric(year)
          gross$budget <- as.numeric(budget)
          gross$budget_curr <- as.character(currency)
          
          business_master <- dplyr::bind_rows(business_master, gross)
    }
}

business_master_keep2 <- business_master

```

```{r}
bus_master2 <- dplyr::bind_rows(business_master_keep1, business_master_keep2) %>% distinct()

#bus_master2 <- business_master_keep1 %>% distinct()

rm(business_master_keep1, business_master_keep2)

total_amount <- bus_master2 %>%
  pull(total) %>%
  pull(amount)

total_currency<- bus_master2 %>%
  pull(total) %>%
  pull(currency)

bus_master2$total_amount <- total_amount
bus_master2$total_currency <- total_currency

bus_master3 <- bus_master2 %>%
  select(-total) %>%
  drop_na(movie_id)

length(unique(bus_master3$movie_id))

#write_csv(bus_master3, "../data_exports/4-14-Business.csv")

rm(gross, response, rows_add, temp_data, dom_gross, intl_gross)

```

### clean budget/box office

```{r}
business_clean <- bus_master3 %>%
  filter(areaName %in% c("World-wide", "International")) %>%
  select(-area) %>%
  pivot_wider(names_from = areaName, values_from = total_amount) %>%
  mutate(Domestic = `World-wide` - International) %>%
  rename(budget_currency = budget_curr)
```

### Add to Filmography Data

```{r}

actor_film_budget <- filmography_data %>%
  left_join(business_clean, by = c("title_ids" = "movie_id"))

# check
c1 <- actor_film_budget %>%
  filter(is.na(film_list))
dim(c1)

c2 <- actor_film_budget %>%
  filter(is.na(title))
dim(c2)

actor_film_budget <- actor_film_budget %>%
  dplyr::select(actor_id, actor_name, film_list, category, title_ids, year, type, 
                budget, budget_currency, `World-wide`, International, Domestic, total_currency) %>%
  rename(title_id = title_ids,
         title = film_list,
         boxoffice_currency = total_currency) %>%
  filter(actor_id %in% cast_ids) %>%
  distinct()

write_csv(actor_film_budget, "../data_exports/Actor_Filmography_with_Business_additions.csv")
```










