---
title: "Actor Success Over Time"
author: "Andrew Ward"
date: "4/18/2022"
output: html_document
---

```{r}
library(readr)
library(tidyverse)
library(plotly)
library(GGally)
library(parcoords)
filmography_awards_masterfile <- read_csv("MCU_filmography_final_version.csv")
head(filmography_awards_masterfile)

```




```{r}
# all movies Box Office Success, Colored by MCU

gT <- ggplot(filmography_awards_masterfile, aes(x = release_date, y = World_Wide, color = MCU, text = title)) +
  geom_point() +
  scale_color_manual(values = c(colors[2], colors[11])) +
  labs(title= "World-Wide Box Office Success", x= "Release Date", y= "World-Wide Box Office")

ggplotly(gT)

```





```{r}
# Include just MCU movies

MCU_films <- filmography_awards_masterfile %>%
  filter(MCU == "MCU") %>%
  filter(type == "Movie") %>%
  group_by(title) %>%
  summarize(BO = World_Wide, Budget = budget_USD, release_date = release_date) %>%
  distinct(title, BO, Budget, release_date) %>%
  mutate(Phase = as.factor(ifelse(release_date < as.Date("2012-05-05"), "One", ifelse(release_date < as.Date("2015-07-18"), "Two", ifelse(release_date < as.Date("2019-07-03"), "Three", "Four")))))

MCU_films$Phase <- relevel(MCU_films$Phase, "One")

MCU_films

```


```{r}
# Box Office Success for MCU movies over time
g2 <- ggplot(MCU_films, aes(x = release_date, y = BO, text = title)) +
  geom_point() +
  labs(title= "Box Office Success of MCU Movies Over Time", x= "Release Date", y= "World-Wide Box Office")

ggplotly(g2)

```


```{r}
# Compare International and Domestic MCU Box Office Success

MCU_IvD <- MCU_films %>%
  distinct(title, release_date, International, Domestic) %>%
  group_by(title) %>%
  summarize(release_date = release_date, International = International, Domestic = Domestic) %>%
  arrange(release_date) %>%
  mutate(title = factor(title, levels = title)) %>%
  dplyr::select(c(title, International, Domestic)) %>%
  pivot_longer(!title, names_to = "I_vs_D", values_to = "BO")

MCU_IvD

gIaD <- ggplot(data= MCU_IvD, aes(x= title, y= BO)) +
  geom_point(aes(color = I_vs_D)) +
  coord_flip()

gIaD

```

```{r}
# Budget vs Box Office Success for MCU movies
gBvB <- ggplot(data= MCU_films, aes(x= Budget, y= BO, text = title, color= Phase)) +
  geom_point() +
  labs(title= "Box Office Success vs Budget of MCU Films", x= "Budget", y= "Box Office")

ggplotly(gBvB)

```

```{r}
tidy_BOB <- MCU_films %>%
  dplyr::select(BO, Budget, Phase) %>%
  rownames_to_column("ID") %>%
  rename(Film_Budget = Budget, Box_Office = BO) %>%
  gather(var, values, -ID, -title, -Phase)

tidy_BOB

standardize <- function(x) (x-mean(x))/sd(x) 
df2 <- tidy_BOB %>% group_by(var) %>%   
  mutate(values = standardize(values)) %>% ungroup()

df2

df2$var <- factor(df2$var, levels = c('Film_Budget', 'Box_Office'))

gslope <- ggplot(df2, aes(x= var, y= values, group= ID, color= Phase)) +
  geom_line() +
  labs(title= "Box Office Success vs Film Budget", x= "Variable", y= "Value")

gslope

```


```{r}
# International vs Domestic Box OFfice Success for MCU movies
gIvD <- ggplot(data= MCU_films, aes(x= Domestic, y= International, text= title)) +
  geom_point()

ggplotly(gIvD)

```



```{r}
# Actor with best Box Office Success overall

group_by_actor <- filmography_awards_masterfile %>%
  filter(type == "Movie") %>%
  group_by(actor_name) %>%
  summarize(Avg_BO_Success = mean(`World-wide`, na.rm= TRUE))

head(group_by_actor)

gABOS <- ggplot(data= group_by_actor, aes(x= actor_name, y= Avg_BO_Success)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

gABOS

```

```{r}
# Actor with best Box Office Success in MCU films vs Non-MCU films

actor_grouped_MCU <- filmography_awards_masterfile %>%
  filter(MCU == "MCU") %>%
  group_by(actor_name) %>%
  summarize(Avg_MCU_BO_Success = mean(World_Wide, na.rm= TRUE)) %>%
  mutate(MCU = "MCU")


actor_grouped_Non <- filmography_awards_masterfile %>%
  filter(MCU == "Non-MCU") %>%
  group_by(actor_name) %>%
  summarize(Avg_Non_BO_Success = mean(World_Wide, na.rm= TRUE)) %>%
  mutate(MCU = "Non-MCU")


avg_MCU_Non <- actor_grouped_MCU %>%
  bind_rows(actor_grouped_Non) %>%
  mutate(Avg_BO_Success = ifelse(MCU == "MCU", Avg_MCU_BO_Success, Avg_Non_BO_Success))


gABOS <- ggplot(data= avg_MCU_Non, aes(x= actor_name, y= Avg_BO_Success)) +
  geom_point(aes(color = MCU)) +
  coord_flip() +
  scale_color_manual(values = c(colors[2], colors[7])) +
  labs(title= "Actor Box Office Success in MCU vs Non-MCU Films", x= "Actor Name", y= "Average Box Office Success")

gABOS


```


```{r}
# Add First MCU Film Date for Each Actor
actor_change1 <- filmography_awards_masterfile %>%
  filter(type == "Movie") %>%
  group_by(actor_name, MCU) %>%
  arrange(actor_name, release_date) %>%
  filter(release_date == min(release_date)) %>%
  mutate(first_MCU = release_date) %>%
  filter(MCU == "MCU") %>%
  ungroup() %>%
  dplyr::select(c(actor_name, first_MCU))


First_MCU_added <- filmography_awards_masterfile %>%
  left_join(actor_change1) %>%
  mutate(joining_phase = ifelse(first_MCU < as.Date("2012-05-05"), "One", ifelse(first_MCU < as.Date("2015-07-18"), "Two", ifelse(first_MCU < as.Date("2019-07-03"), "Three", "Four")))) %>%
  mutate(joining_phase = factor(joining_phase, levels= c("One", "Two", "Three", "Four")))

First_MCU_added$joining_phase <- relevel(First_MCU_added$joining_phase, "One")

```


```{r}
# Actor Success Before and After First MCU Film

before <- First_MCU_added %>%
  filter(MCU == "Non-MCU") %>%
  filter(release_date < first_MCU)

after <- First_MCU_added %>%
  filter(MCU == "Non-MCU") %>%
  filter(release_date > first_MCU)

before <- before %>%
  group_by(actor_name) %>%
  summarize(Avg_before_BO_Success = mean(World_Wide, na.rm= TRUE)) %>%
  mutate(BoA = "before")

after <- after %>%
  group_by(actor_name) %>%
  summarize(Avg_after_BO_Success = mean(World_Wide, na.rm= TRUE)) %>%
  mutate(BoA = "after")

BaA <- before %>%
  bind_rows(after) %>%
  mutate(Avg_BO_Success = ifelse(BoA == "before", Avg_before_BO_Success, Avg_after_BO_Success))



gBaA <- ggplot(data= BaA, aes(x= actor_name, y= Avg_BO_Success)) +
  geom_point(aes(color = BoA)) +
  coord_flip() +
  scale_color_manual(values = c(colors[6], colors[11])) +
  labs(title= "Average Box Office Success Before vs After First MCU Film", x= "Actor Name", y= "Average Box Office Success")

gBaA

```

```{r}
# Parallel Coordinate Plot for Actors and Various Stats

award_nom_count <- filmography_awards_masterfile %>%
  group_by(actor_name) %>%
  summarize(Award_Nominations = length(na.omit(winner)))


master_MCU <- filmography_awards_masterfile %>%
  filter(MCU == "MCU")

master_Non <- filmography_awards_masterfile %>%
  filter(MCU == "Non-MCU")

MCU_film_total <- master_MCU %>%
  group_by(actor_name) %>%
  summarize(MCU_film_count = length(title), MCU_Avg_BoxOffice = mean(World_Wide, na.rm= TRUE), MCU_Avg_Budget = mean(budget_USD, na.rm= TRUE))

Non_film_total <- master_Non %>%
  group_by(actor_name) %>%
  summarize(film_count = length(title), Avg_BoxOffice = mean(World_Wide, na.rm= TRUE), Avg_Budget = mean(budget_USD, na.rm= TRUE))

actor_joining_phase <- First_MCU_added %>%
  group_by(actor_name) %>%
  summarize(joining_phase = joining_phase)


PC_data <- award_nom_count %>%
  left_join(MCU_film_total) %>%
  left_join(Non_film_total) %>%
  left_join(actor_joining_phase)


ggparcoord(PC_data, columns= c(3, 6, 4, 7, 5, 8, 2), alphaLines= .1, scale= "uniminmax", groupColumn= 9)  +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title= "Actor Comparison Over Multiple Variables")

```


```{r}
PC_data %>%
  parcoords(rownames= FALSE, brushMode = "1D-axes", reorderable = TRUE, queue = TRUE, alpha= .5, color= list(colorBy = "joining_phase", colorScale= "scaleOrdinal", colorScheme= "schemeCategory10"), withD3 = TRUE)


```




















